### ISSUE TITLE
SCSS modules in CommonJS

### ISSUE THREAD

**Issue by Jinjiang** [haijie-x/vite-plugin-cjs2esm#1]
Hi, I'm from this issue https://github.com/vitejs/vite/issues/13298 hope you don't mind.

Here is a real case that still got an error:

You can install this package via:

```bash
npm config set '@teambit:registry' https://node.bit.cloud
pnpm i @teambit/design.themes.base-theme
```

after that, import this package as a React component, you still got the error with your plugin

```tsx
import ReactDOM from 'react-dom/client'
import { BaseTheme } from '@teambit/design.themes.base-theme';

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <BaseTheme>
    <h1>Hello World</h1>
  </BaseTheme>,
)
```

the error:

```
index.ts:3  Uncaught TypeError: Cannot read properties of undefined (reading 'circularFont')
    at node_modules/.pnpm/@teambit+design.themes.base-theme@0.1.3_@testing-library+react@12.1.5_react-dom@18.2.0_react@18.2.0/node_modules/@teambit/design.themes.base-theme/dist/circular-font/index.js (index.ts:3:39)
    at __require (chunk-SPYXDAPC.js?v=7c977e59:9:50)
    at node_modules/.pnpm/@teambit+design.themes.base-theme@0.1.3_@testing-library+react@12.1.5_react-dom@18.2.0_react@18.2.0/node_modules/@teambit/design.themes.base-theme/dist/base-theme.js (base-theme.tsx:9:1)
    at __require (chunk-SPYXDAPC.js?v=7c977e59:9:50)
    at node_modules/.pnpm/@teambit+design.themes.base-theme@0.1.3_@testing-library+react@12.1.5_react-dom@18.2.0_react@18.2.0/node_modules/@teambit/design.themes.base-theme/dist/index.js (index.ts:3:1)
    at __require (chunk-SPYXDAPC.js?v=7c977e59:9:50)
    at index.ts:3:29
```

Do you think it could be possibly supported by your plugin?

Thanks.

**Comment by Jinjiang** [comment]
FYI, I think the key part in this package which triggers the error is:

```js
// node_modules\@teambit\design.themes.base-theme\dist\circular-font\index.js
const circular_font_module_scss_1 = __importDefault(require("./circular-font.module.scss"));
```

**Comment by haijie-x** [comment]
Nice to meet you again and thank you for your feedback. The main problem here is that the modules imported have already been bundled, it wrapped by `__importDefault` which affects the parsing process by `plugin`, I hacked the following code in the dist directory and found that it works. I will try my best to solve this problem and adapt to this situation.
<img width="684" alt="image" src="https://github.com/haijie-x/vite-plugin-cjs2esm/assets/98948357/af83f648-85f7-468e-a69e-644720d0d5ff">

<img width="1357" alt="image" src="https://github.com/haijie-x/vite-plugin-cjs2esm/assets/98948357/3639ca24-0116-4abd-802f-59d3587d87b0">

**Comment by haijie-x** [comment]
Sorry, I think my analysis was wrong yesterday. The actual error should be that maybe we forgot to configure the vite plugin, which is tricky.

`vite.config.ts`
```js
export default defineConfig({
 // ... 
  plugins: [ 
    // ...
    cjs2esm.vitePlugin()
  ],
  optimizeDeps: {
    esbuildOptions: {
      plugins: [
        cjs2esm.esbuildPlugin({
          filter: /!react/
        })
      ]
    }
  }
})
```

and it works.
<img width="1367" alt="image" src="https://github.com/haijie-x/vite-plugin-cjs2esm/assets/98948357/636c8bf9-2e49-4f54-87f3-82e3d90c0ba0">

**Comment by haijie-x** [comment]
> Sorry, I think my analysis was wrong yesterday. The actual error should be that maybe we forgot to configure the vite plugin, we both made that mistake.
> 
> `vite.config.ts`
> ```js
> export default defineConfig({
>  // ... 
>   plugins: [ 
>     // ...
>     cjs2esm.vitePlugin()
>   ],
>   optimizeDeps: {
>     esbuildOptions: {
>       plugins: [
>         cjs2esm.esbuildPlugin({
>           filter: /!react/
>         })
>       ]
>     }
>   }
> })
> ```
> 
> and it works.
> <img width="1367" alt="image" src="https://github.com/haijie-x/vite-plugin-cjs2esm/assets/98948357/636c8bf9-2e49-4f54-87f3-82e3d90c0ba0">
> 
> 

i will fix **react** exports error. you can add filter temporarily to avoid this pre build error.

**Comment by Jinjiang** [comment]
Would you mind checking again? Here is my reproduction:

https://github.com/Jinjiang/reproductions/tree/vite-plugin-cjs2esm-20230613

The error log:

<img width="531" alt="image" src="https://github.com/haijie-x/vite-plugin-cjs2esm/assets/206848/80fd99c2-8497-44f5-97c0-2769d70e921e">

```
import a css module {foo: '_foo_iyjzy_1', bar: '_bar_iyjzy_5'}
require a css module {__esModule: true}

Uncaught TypeError: Cannot read properties of undefined (reading 'circularFont')
    at node_modules/.pnpm/@teambit+design.themes.base-theme@0.1.3_@testing-library+react@12.1.5_react-dom@18.2.0_react@18.2.0/node_modules/@teambit/design.themes.base-theme/dist/circular-font/index.js (index.ts:3:39)
    at __require (chunk-QYDSUZJS.js?v=49929e0c:9:50)
    at node_modules/.pnpm/@teambit+design.themes.base-theme@0.1.3_@testing-library+react@12.1.5_react-dom@18.2.0_react@18.2.0/node_modules/@teambit/design.themes.base-theme/dist/base-theme.js (base-theme.tsx:9:1)
    at __require (chunk-QYDSUZJS.js?v=49929e0c:9:50)
    at node_modules/.pnpm/@teambit+design.themes.base-theme@0.1.3_@testing-library+react@12.1.5_react-dom@18.2.0_react@18.2.0/node_modules/@teambit/design.themes.base-theme/dist/index.js (index.ts:3:1)
    at __require (chunk-QYDSUZJS.js?v=49929e0c:9:50)
    at index.ts:3:29
```

Thanks.

**Comment by haijie-x** [comment]
> Sorry, I think my analysis was wrong yesterday. The actual error should be that maybe we forgot to configure the vite plugin, we both made that mistake.
> 
> `vite.config.ts`
> 
> ```js
> export default defineConfig({
>  // ... 
>   plugins: [ 
>     // ...
>     cjs2esm.vitePlugin()
>   ],
>   optimizeDeps: {
>     esbuildOptions: {
>       plugins: [
>         cjs2esm.esbuildPlugin({
>           // ❗️❗️❗️❗️❗️❗️ following means that let `esbuild` handle cjs in `react` lib
>           filter: /!react/
>         })
>       ]
>     }
>   }
> })
> ```
> 
> and it works. <img alt="image" width="1367" src="https://user-images.githubusercontent.com/98948357/244590248-636c8bf9-2e49-4f54-87f3-82e3d90c0ba0.png">

I am debugging and found that import result is undefined although it work. And I also think it needs vite support. The plugin level can not do transform.

**Comment by Jinjiang** [comment]
https://github.com/vitejs/vite/pull/13519
It has been solved here. I will close this issue. Thanks for the help.
